### ISSUE TITLE
No se pueden cargar listas ni cursos de codigofacilito

### ISSUE THREAD

**Issue by sbarcelona11** [ezeqescobar/plugin.video.codigofacilito.com#1]
No se cargan cursos ni listas de codigofacilito, uso tu plugin desde Kodi.

**Comment by ezeqescobar** [comment]
Buenas, en estos dias voy a arreglar eso...voy a tener que mover el scrapper a un servidor externo para evitar tener que esperar los cambios en el repo de kodi. Gracias por avisar

**Comment by sbarcelona11** [comment]
Eze,

Intente cambiar tu script, agregar un nuevo metodo para poder hacer login
antes de scrapear, pero por alguna razon, me explota cuando hace
plugin.run()

Espero a que realices los cambios.

Saludos

Sebastian

**Comment by ezeqescobar** [comment]
Ya esta solucionado, pronto se actualizará en el repo oficial. Gracias y perdón por la demora.

**Comment by jjgomera** [comment]
Hola,

me da el mismo error, no encuentra ningún curso.

Estoy usando la version del plugin del repo oficial de kodi que tiene el último commit de github sobre kodi v.15 en una raspberry 3 con raspbian.

Saludos

**Comment by ezeqescobar** [comment]
Al parecer los de CF bloquearon las peticiones desde mi dominio, pero ya está solucionado (haciendo proxy en otro =\ ).

Saludos

**Comment by jjgomera** [comment]
Perfecto, ya funciona

Gracias
